### PR TITLE
Add url-archiver tool 

### PR DESCRIPTION
**Pull request by adampirani**
Tool will to go through a list of paths and save them to the internet archiver

### CODE REVIEW

**Comment by adampirani** [comment]
cc: @ibrlaurie & @khdelphine

**Comment by dcwalk** [comment]
Looks awesome! I think we want to remove the data currently in `paths.txt`, `missingFiles.txt`, also @titaniumbones -- this should go in the harvesting tools repo (https://github.com/edgi-govdata-archiving/harvesting-tools) now I believe?

**Comment by adampirani** [comment]
I agree. :+1:

**Comment by titaniumbones** [comment]
yeah, @aplikesbikes I'm going to close this and hope you'll put it over in harvesting-tools now, as suggested? We are hoping to eventually build these tools into the event webapp (so you could prepopulate your zipfolder with the tool you want -- cool right?), so it makes sense to have them *(a) in a separate place, and (b) all together. thank you!

**Review by titaniumbones — COMMENTED** [review]
I agree, belongs in harvesting-tools, let's put it there!! Thank you @aplikesbikes !!

**Pull request closed without merging**
